spring:
    datasource:
        url: jdbc:postgresql://192.168.45.143:3308/postgres
        username: postgres
        password: 1234
        driver-class-name : org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgresPlusDialect
